/* eslint-disable */
import { LZWEncoder, type ByteSink } from './LZWEncoder';
import { NeuQuant } from './NeuQuant';

const chr: Record<number, string> = {};
for (let i = 0; i < 256; i++) chr[i] = String.fromCharCode(i);

export class ByteArray implements ByteSink {
  bin: number[] = [];
  getData(): string {
    let v = '';
    for (let i = 0; i < this.bin.length; i++) v += chr[this.bin[i]];
    return v;
  }
  writeByte(val: number): void {
    this.bin.push(val);
  }
  writeUTFBytes(s: string): void {
    for (let i = 0; i < s.length; i++) this.writeByte(s.charCodeAt(i));
  }
  writeBytes(arr: ArrayLike<number>, offset?: number, length?: number): void {
    const end = length ?? arr.length;
    for (let i = offset ?? 0; i < end; i++) this.writeByte(arr[i]);
  }
}

export class GIFEncoder {
  private width = 0;
  private height = 0;
  private transparent: number | null = null;
  private transIndex = 0;
  private repeat = -1;
  private delay = 0;
  private started = false;
  private out!: ByteArray;
  private image: Uint8ClampedArray | null = null;
  private pixels: number[] | null = null;
  private indexedPixels: number[] | null = null;
  private colorDepth = 0;
  private colorTab: number[] | null = null;
  private usedEntry: boolean[] = [];
  private palSize = 7;
  private dispose = -1;
  private firstFrame = true;
  private sizeSet = false;
  private sample = 10;
  private comment = 'Generated by gifloopcoder';
  private maxColors = 256;

  setDelay(ms: number): void {
    this.delay = Math.round(ms / 10);
  }
  setDispose(code: number): void {
    if (code >= 0) this.dispose = code;
  }
  setRepeat(iter: number): void {
    if (iter >= 0) this.repeat = iter;
  }
  setTransparent(c: number | null): void {
    this.transparent = c;
  }
  setComment(c: string): void {
    this.comment = c;
  }

  setFrameRate(fps: number): void {
    if (fps != 0xf) this.delay = Math.round(100 / fps);
  }

  setQuality(quality: number): void {
    if (quality < 1) quality = 1;
    this.sample = quality;
  }

  setSize(w: number, h: number): void {
    if (this.started && !this.firstFrame) return;
    this.width = w < 1 ? 320 : w;
    this.height = h < 1 ? 240 : h;
    this.sizeSet = true;
  }

  setMaxColors(colors: number): void {
    this.maxColors = colors;
  }

  start(): boolean {
    this.reset();
    this.out = new ByteArray();
    let ok = true;
    try {
      this.out.writeUTFBytes('GIF89a');
    } catch (_e) {
      ok = false;
    }
    return (this.started = ok);
  }

  addFrame(im: CanvasRenderingContext2D | Uint8ClampedArray, isImageData = false): boolean {
    if (im === null || !this.started || this.out === null) {
      throw new Error('Please call start method before calling addFrame');
    }
    let ok = true;
    try {
      if (!isImageData) {
        const ctx = im as CanvasRenderingContext2D;
        this.image = ctx.getImageData(0, 0, ctx.canvas.width, ctx.canvas.height).data;
        if (!this.sizeSet) this.setSize(ctx.canvas.width, ctx.canvas.height);
      } else {
        this.image = im as Uint8ClampedArray;
      }
      this.getImagePixels();
      this.analyzePixels();
      if (this.firstFrame) {
        this.writeLSD();
        this.writePalette();
        if (this.repeat >= 0) this.writeNetscapeExt();
      }
      this.writeGraphicCtrlExt();
      if (this.comment !== '') this.writeCommentExt();
      this.writeImageDesc();
      if (!this.firstFrame) this.writePalette();
      this.writePixels();
      this.firstFrame = false;
    } catch (_e) {
      ok = false;
    }
    return ok;
  }

  finish(): boolean {
    if (!this.started) return false;
    let ok = true;
    this.started = false;
    try {
      this.out.writeByte(0x3b);
    } catch (_e) {
      ok = false;
    }
    return ok;
  }

  stream(): ByteArray {
    return this.out;
  }

  private reset(): void {
    this.transIndex = 0;
    this.image = null;
    this.pixels = null;
    this.indexedPixels = null;
    this.colorTab = null;
    this.firstFrame = true;
  }

  private analyzePixels(): void {
    const pixels = this.pixels!;
    const len = pixels.length;
    const nPix = len / 3;
    this.indexedPixels = [];
    const nq = new NeuQuant(pixels, len, this.sample);
    nq.setMaxColors(this.maxColors);
    this.colorTab = nq.process();
    let k = 0;
    for (let j = 0; j < nPix; j++) {
      const index = nq.map(pixels[k++] & 0xff, pixels[k++] & 0xff, pixels[k++] & 0xff);
      this.usedEntry[index] = true;
      this.indexedPixels[j] = index;
    }
    this.pixels = null;
    this.colorDepth = 8;
    this.palSize = 7;
    if (this.transparent !== null) {
      this.transIndex = this.findClosest(this.transparent);
    }
  }

  private findClosest(c: number): number {
    if (this.colorTab === null) return -1;
    const r = (c & 0xff0000) >> 16;
    const g = (c & 0x00ff00) >> 8;
    const b = c & 0x0000ff;
    let minpos = 0;
    let dmin = 256 * 256 * 256;
    const len = this.colorTab.length;
    for (let i = 0; i < len; ) {
      const dr = r - (this.colorTab[i++] & 0xff);
      const dg = g - (this.colorTab[i++] & 0xff);
      const db = b - (this.colorTab[i] & 0xff);
      const d = dr * dr + dg * dg + db * db;
      const index = i / 3;
      if (this.usedEntry[index] && d < dmin) {
        dmin = d;
        minpos = index;
      }
      i++;
    }
    return minpos;
  }

  private getImagePixels(): void {
    const w = this.width;
    const h = this.height;
    const pixels: number[] = [];
    const data = this.image!;
    let count = 0;
    for (let i = 0; i < h; i++) {
      for (let j = 0; j < w; j++) {
        const b = i * w * 4 + j * 4;
        pixels[count++] = data[b];
        pixels[count++] = data[b + 1];
        pixels[count++] = data[b + 2];
      }
    }
    this.pixels = pixels;
  }

  private writeGraphicCtrlExt(): void {
    this.out.writeByte(0x21);
    this.out.writeByte(0xf9);
    this.out.writeByte(4);
    let transp: number;
    let disp: number;
    if (this.transparent === null) {
      transp = 0;
      disp = 0;
    } else {
      transp = 1;
      disp = 2;
    }
    if (this.dispose >= 0) {
      disp = this.dispose & 7;
    }
    disp <<= 2;
    this.out.writeByte(0 | disp | 0 | transp);
    this.WriteShort(this.delay);
    this.out.writeByte(this.transIndex);
    this.out.writeByte(0);
  }

  private writeCommentExt(): void {
    this.out.writeByte(0x21);
    this.out.writeByte(0xfe);
    this.out.writeByte(this.comment.length);
    this.out.writeUTFBytes(this.comment);
    this.out.writeByte(0);
  }

  private writeImageDesc(): void {
    this.out.writeByte(0x2c);
    this.WriteShort(0);
    this.WriteShort(0);
    this.WriteShort(this.width);
    this.WriteShort(this.height);
    if (this.firstFrame) {
      this.out.writeByte(0);
    } else {
      this.out.writeByte(0x80 | 0 | 0 | 0 | this.palSize);
    }
  }

  private writeLSD(): void {
    this.WriteShort(this.width);
    this.WriteShort(this.height);
    this.out.writeByte(0x80 | 0x70 | 0x00 | this.palSize);
    this.out.writeByte(0);
    this.out.writeByte(0);
  }

  private writeNetscapeExt(): void {
    this.out.writeByte(0x21);
    this.out.writeByte(0xff);
    this.out.writeByte(11);
    this.out.writeUTFBytes('NETSCAPE' + '2.0');
    this.out.writeByte(3);
    this.out.writeByte(1);
    this.WriteShort(this.repeat);
    this.out.writeByte(0);
  }

  private writePalette(): void {
    this.out.writeBytes(this.colorTab!);
    const n = 3 * 256 - this.colorTab!.length;
    for (let i = 0; i < n; i++) this.out.writeByte(0);
  }

  private WriteShort(pValue: number): void {
    this.out.writeByte(pValue & 0xff);
    this.out.writeByte((pValue >> 8) & 0xff);
  }

  private writePixels(): void {
    const enc = new LZWEncoder(this.width, this.height, this.indexedPixels!, this.colorDepth);
    enc.encode(this.out);
  }
}
